version: '3'
services:
  service-discovery:
    image: service-discovery:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  service1:
    image: service1:latest
    ports:
      - "9081:9081"
    networks:
      - microservices-network

  service2:
    image: service2:latest
    ports:
      - "9082:9082"
    networks:
      - microservices-network

  api-gateway:
    image: api-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
