spring:
  application:
    name: service1

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true