name: microservice pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot for Beginner
    runs-on: self-hosted
    #strategy:
     # matrix:
      #  service: [service1, service2, service-discovery, api_gateway]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build and test service-discovery
      working-directory: service-discovery
      run: |
        mvn clean package
        

    - name: Build and push Docker image 
      working-directory: service-discovery
      run: |
        sudo docker build -t service-discovery:latest .

    - name: run docker image
      run:
        sudo docker run -d -p 8761:8761 service-discovery:latest

    - name: Build and test service1
      working-directory: service1
      run: |
        mvn clean package

    - name: Build and push Docker image 
      working-directory: service1
      run: |
        sudo docker build -t service1:latest .

    - name: Build and test service2
      working-directory: service2
      run: |
        mvn clean package
        

    - name: Build and push Docker image 
      working-directory: service2
      run: |
        sudo docker build -t service2:latest .

    - name: Build and test api-gateway
      working-directory: api-gateway
      run: |
        mvn clean package
        

    - name: Build and push Docker image 
      working-directory: api-gateway
      run: |
        sudo docker build -t api-gateway:latest .

    - name: Deploy with Docker Compose
      working-directory: ./  
      run: |
        sudo docker-compose down
        sudo docker-compose up -d

    
        
