name: microservice pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot for Beginner
    runs-on: self-hosted
    strategy:
      matrix:
        service: [service1, service2, service-discovery, api_gateway]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build and test ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: |
        mvn clean package
        

    - name: Build and push Docker image 
      working-directory: ${{ matrix.service }}
      run: |
        sudo docker build -t ${{ matrix.service }}:latest .

    - name: Deploy with Docker Compose
      working-directory: ./  
      run: |
        sudo docker-compose down
        sudo docker-compose up -d

    
        
